/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package agent

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"strconv"
	"strings"
	"testing"
)

func TestIsGeneratedGoFile(t *testing.T) {
	ws := t.TempDir()
	write := func(rel, content string) {
		full := filepath.Join(ws, rel)
		_ = os.MkdirAll(filepath.Dir(full), 0o755)
		if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write("api/zz_generated.deepcopy.go", "package v1\n")
	write("pkg/x/thing.pb.go", "package x\n")
	write("pkg/x/gen.go", "// Code generated by foo. DO NOT EDIT.\npackage x\n")
	write("pkg/x/hand.go", "package x\n\nfunc F() {}\n")

	cases := map[string]bool{
		"api/zz_generated.deepcopy.go": true,
		"pkg/x/thing.pb.go":            true,
		"pkg/x/gen.go":                 true,
		"pkg/x/hand.go":                false,
	}
	for path, want := range cases {
		if got := isGeneratedGoFile(ws, path); got != want {
			t.Errorf("isGeneratedGoFile(%q)=%v want %v", path, got, want)
		}
	}
}

func TestChangedNonTestGoFiles(t *testing.T) {
	ws := t.TempDir()
	for _, p := range []string{"pkg/x/hand.go", "pkg/x/hand_test.go", "pkg/x/zz_generated.deepcopy.go"} {
		full := filepath.Join(ws, p)
		_ = os.MkdirAll(filepath.Dir(full), 0o755)
		_ = os.WriteFile(full, []byte("package x\n"), 0o644)
	}
	runner := func(_ context.Context, _ string, _ []string, name string, args ...string) (string, error) {
		return " M pkg/x/hand.go\x00 M pkg/x/hand_test.go\x00 M pkg/x/zz_generated.deepcopy.go\x00 M docs/readme.md\x00", nil
	}
	got := changedNonTestGoFiles(context.Background(), ws, runner)
	if len(got) != 1 || got[0] != "pkg/x/hand.go" {
		t.Fatalf("changedNonTestGoFiles = %v, want [pkg/x/hand.go]", got)
	}
}

func TestCheckTestPresence(t *testing.T) {
	ws := t.TempDir()
	full := filepath.Join(ws, "internal/controller/x.go")
	_ = os.MkdirAll(filepath.Dir(full), 0o755)
	_ = os.WriteFile(full, []byte("package controller\n\nfunc waitForIdle() {}\n"), 0o644)

	statusOut := " M internal/controller/x.go\x00"
	diffOut := "diff --git a/internal/controller/x.go b/internal/controller/x.go\n" +
		"@@ -0,0 +1,3 @@\n+package controller\n+\n+func waitForIdle() {}\n"
	runner := func(_ context.Context, _ string, _ []string, name string, args ...string) (string, error) {
		if name == "git" && len(args) > 0 && args[0] == "status" {
			return statusOut, nil
		}
		if name == "git" && len(args) > 1 && args[0] == "diff" && (args[1] == "HEAD" || args[1] == "-U0") {
			return diffOut, nil
		}
		return "", nil
	}

	failed, out := checkTestPresence(context.Background(), ws, runner)
	if !failed {
		t.Fatal("expected presence failure for new func with no test")
	}
	if !strings.Contains(out, "internal/controller") || !strings.Contains(out, "waitForIdle") {
		t.Errorf("feedback should name the package and the new func; got:\n%s", out)
	}
}

// TestCheckTestPresence_PassesWhenTestChanged is updated to reflect the new
// per-symbol requirement: the changed _test.go must reference the added func by
// name (here "New") for the package to pass. The old assertion ("any changed
// _test.go passes") encoded the loosened per-package behavior we are
// deliberately tightening, so we now write the test file's content to disk so
// the per-symbol check can read it and find the reference.
func TestCheckTestPresence_PassesWhenTestChanged(t *testing.T) { //nolint:dupl
	ws := t.TempDir()
	_ = os.MkdirAll(filepath.Join(ws, "pkg/x"), 0o755)
	_ = os.WriteFile(filepath.Join(ws, "pkg/x/x.go"), []byte("package x\nfunc New(){}\n"), 0o644)
	// The test file references "New" so the per-symbol check is satisfied.
	_ = os.WriteFile(filepath.Join(ws, "pkg/x/x_test.go"),
		[]byte("package x\nimport \"testing\"\nfunc TestNew(t *testing.T) { New() }\n"), 0o644)
	statusOut := " M pkg/x/x.go\x00 M pkg/x/x_test.go\x00"
	// git diff HEAD -- file: plain diff (no -U0 flag) — used by addedFuncNames
	diffOut := "@@ -0,0 +1,1 @@\n+func New() {}\n"
	// git diff -U0 HEAD -- file: used by modifiedFuncNames (no hunk-context func here)
	diffU0Out := "@@ -0,0 +1,1 @@\n+func New() {}\n"
	runner := func(_ context.Context, _ string, _ []string, name string, args ...string) (string, error) {
		switch {
		case name == "git" && args[0] == "status":
			return statusOut, nil
		case name == "git" && args[0] == "diff" && len(args) > 2 && args[1] == "-U0" && args[2] == "HEAD":
			return diffU0Out, nil
		case name == "git" && args[0] == "diff" && len(args) > 1 && args[1] == "HEAD":
			return diffOut, nil
		}
		return "", nil
	}
	failed, _ := checkTestPresence(context.Background(), ws, runner)
	if failed {
		t.Fatal("presence must pass when the package has a changed _test.go referencing New")
	}
}

// TestCheckTestPresence_UnrelatedTestDoesNotExempt verifies that a changed
// _test.go that references only an unrelated symbol (Bar) does not exempt an
// added func (Foo) from the per-symbol presence check.
func TestCheckTestPresence_UnrelatedTestDoesNotExempt(t *testing.T) {
	ws := t.TempDir()
	_ = os.MkdirAll(filepath.Join(ws, "internal/controller"), 0o755)
	_ = os.WriteFile(filepath.Join(ws, "internal/controller/x.go"),
		[]byte("package controller\nfunc Foo() {}\n"), 0o644)
	// y_test.go references Bar only — Foo is unreferenced.
	_ = os.WriteFile(filepath.Join(ws, "internal/controller/y_test.go"),
		[]byte("package controller\nfunc TestBar(t interface{}) { _ = Bar }\n"), 0o644)

	statusOut := " M internal/controller/x.go\x00 M internal/controller/y_test.go\x00"
	// git diff HEAD -- x.go: plain diff, adds func Foo
	diffOut := "diff --git a/internal/controller/x.go b/internal/controller/x.go\n" +
		"@@ -0,0 +1,2 @@\n+package controller\n+func Foo() {}\n"
	// git diff -U0 HEAD -- x.go: -U0 diff, no trailing func context on this hunk
	diffU0Out := "@@ -0,0 +1,2 @@\n+package controller\n+func Foo() {}\n"

	runner := func(_ context.Context, _ string, _ []string, name string, args ...string) (string, error) {
		switch {
		case name == "git" && args[0] == "status":
			return statusOut, nil
		case name == "git" && args[0] == "diff" && len(args) > 2 && args[1] == "-U0" && args[2] == "HEAD":
			return diffU0Out, nil
		case name == "git" && args[0] == "diff" && len(args) > 1 && args[1] == "HEAD":
			return diffOut, nil
		}
		return "", nil
	}

	failed, out := checkTestPresence(context.Background(), ws, runner)
	if !failed || !strings.Contains(out, "Foo") {
		t.Fatalf("want failure naming Foo, got failed=%v out=%q", failed, out)
	}
}

// TestCheckTestPresence_ReferencingTestPasses verifies that a changed _test.go
// that references the added func Foo by name satisfies the per-symbol check.
func TestCheckTestPresence_ReferencingTestPasses(t *testing.T) { //nolint:dupl
	ws := t.TempDir()
	_ = os.MkdirAll(filepath.Join(ws, "pkg/x"), 0o755)
	_ = os.WriteFile(filepath.Join(ws, "pkg/x/x.go"),
		[]byte("package x\nfunc Foo() {}\n"), 0o644)
	// x_test.go references Foo — presence is satisfied.
	_ = os.WriteFile(filepath.Join(ws, "pkg/x/x_test.go"),
		[]byte("package x\nfunc TestFoo(t interface{}) { Foo() }\n"), 0o644)

	statusOut := " M pkg/x/x.go\x00 M pkg/x/x_test.go\x00"
	diffOut := "@@ -0,0 +1,2 @@\n+package x\n+func Foo() {}\n"
	diffU0Out := "@@ -0,0 +1,2 @@\n+package x\n+func Foo() {}\n"

	runner := func(_ context.Context, _ string, _ []string, name string, args ...string) (string, error) {
		switch {
		case name == "git" && args[0] == "status":
			return statusOut, nil
		case name == "git" && args[0] == "diff" && len(args) > 2 && args[1] == "-U0" && args[2] == "HEAD":
			return diffU0Out, nil
		case name == "git" && args[0] == "diff" && len(args) > 1 && args[1] == "HEAD":
			return diffOut, nil
		}
		return "", nil
	}

	failed, _ := checkTestPresence(context.Background(), ws, runner)
	if failed {
		t.Fatal("a test referencing Foo should satisfy presence")
	}
}

// TestCheckTestPresence_ExportedFlaggedUnexportedAcceptedWithChangedTest pins
// the #1329 split: with a changed test present, an EXPORTED net-new function
// still requires a by-name reference (flagged if missing), while an UNEXPORTED
// helper is accepted as covered transitively. Package pkg/model adds Classify
// (exported) and extractRepo (unexported); the changed test names neither.
func TestCheckTestPresence_ExportedFlaggedUnexportedAcceptedWithChangedTest(t *testing.T) {
	ws := t.TempDir()
	_ = os.MkdirAll(filepath.Join(ws, "pkg/model"), 0o755)
	_ = os.WriteFile(filepath.Join(ws, "pkg/model/classifier.go"),
		[]byte("package model\nfunc Classify() {}\nfunc extractRepo() {}\n"), 0o644)
	// Changed test names neither Classify nor extractRepo.
	_ = os.WriteFile(filepath.Join(ws, "pkg/model/classifier_test.go"),
		[]byte("package model\nimport \"testing\"\nfunc TestSomething(t *testing.T) { _ = 1 }\n"), 0o644)

	statusOut := " M pkg/model/classifier.go\x00 M pkg/model/classifier_test.go\x00"
	diffOut := "@@ -0,0 +1,3 @@\n+package model\n+func Classify() {}\n+func extractRepo() {}\n"
	runner := func(_ context.Context, _ string, _ []string, name string, args ...string) (string, error) {
		switch {
		case name == "git" && args[0] == "status":
			return statusOut, nil
		case name == "git" && args[0] == "diff" && len(args) > 2 && args[1] == "-U0" && args[2] == "HEAD":
			return diffOut, nil
		case name == "git" && args[0] == "diff" && len(args) > 1 && args[1] == "HEAD":
			return diffOut, nil
		}
		return "", nil
	}

	failed, out := checkTestPresence(context.Background(), ws, runner)
	if !failed {
		t.Fatal("expected failure: exported Classify has no test naming it")
	}
	if !strings.Contains(out, "Classify") {
		t.Errorf("feedback should flag the exported Classify; got:\n%s", out)
	}
	if strings.Contains(out, "extractRepo") {
		t.Errorf("unexported extractRepo must be accepted (changed test present), not flagged; got:\n%s", out)
	}
}

// TestCheckTestPresence_UnexportedHelperFlaggedWithoutChangedTest pins the
// honest boundary of #1329: an unexported helper is still flagged when the
// package has NO changed test at all (nothing exercises it).
func TestCheckTestPresence_UnexportedHelperFlaggedWithoutChangedTest(t *testing.T) {
	ws := t.TempDir()
	_ = os.MkdirAll(filepath.Join(ws, "pkg/model"), 0o755)
	_ = os.WriteFile(filepath.Join(ws, "pkg/model/classifier.go"),
		[]byte("package model\nfunc extractRepo() {}\n"), 0o644)

	statusOut := " M pkg/model/classifier.go\x00" // no changed _test.go
	diffOut := "@@ -0,0 +1,2 @@\n+package model\n+func extractRepo() {}\n"
	runner := func(_ context.Context, _ string, _ []string, name string, args ...string) (string, error) {
		switch {
		case name == "git" && args[0] == "status":
			return statusOut, nil
		case name == "git" && args[0] == "diff" && len(args) > 2 && args[1] == "-U0" && args[2] == "HEAD":
			return diffOut, nil
		case name == "git" && args[0] == "diff" && len(args) > 1 && args[1] == "HEAD":
			return diffOut, nil
		}
		return "", nil
	}

	failed, out := checkTestPresence(context.Background(), ws, runner)
	if !failed || !strings.Contains(out, "extractRepo") {
		t.Fatalf("unexported helper with no changed test must be flagged; got failed=%v out=%q", failed, out)
	}
}

// TestCheckTestPresence_ModifiedFuncDoesNotNeedTest verifies that a
// body-modified function (no net-new +func line) does NOT demand a named
// test. Behavior-preserving edits to existing functions are covered by
// Layer 2 (mutation survival) where package tests exist, and by CI's full
// suite everywhere; demanding a fresh named test for every touched call
// site made refactors un-landable for mid-size coders (the #921 run burned
// all three gate attempts on envtest-package tests the coder workspace
// cannot even run).
func TestCheckTestPresence_ModifiedFuncDoesNotNeedTest(t *testing.T) {
	ws := t.TempDir()
	_ = os.MkdirAll(filepath.Join(ws, "pkg/diff"), 0o755)
	_ = os.WriteFile(filepath.Join(ws, "pkg/diff/diff.go"),
		[]byte("package diff\nfunc DiffNameOnly() string { return \"new\" }\n"), 0o644)
	// No changed _test.go at all.

	statusOut := " M pkg/diff/diff.go\x00"
	// git diff -- diff.go: body changed but no +func line
	diffOut := "diff --git a/pkg/diff/diff.go b/pkg/diff/diff.go\n" +
		"@@ -1,2 +1,2 @@ func DiffNameOnly() string {\n-\treturn \"old\"\n+\treturn \"new\"\n"
	// git diff -U0 -- diff.go: hunk header carries the enclosing func name
	diffU0Out := "@@ -1,1 +1,1 @@ func DiffNameOnly() string {\n-\treturn \"old\"\n+\treturn \"new\"\n"

	runner := func(_ context.Context, _ string, _ []string, name string, args ...string) (string, error) {
		switch {
		case name == "git" && args[0] == "status":
			return statusOut, nil
		case name == "git" && args[0] == "diff" && len(args) > 1 && args[1] == "-U0":
			return diffU0Out, nil
		case name == "git" && args[0] == "diff":
			return diffOut, nil
		}
		return "", nil
	}

	failed, out := checkTestPresence(context.Background(), ws, runner)
	if failed {
		t.Fatalf("body-modified func must not demand a test; got failure:\n%s", out)
	}
}

func TestNeuterChangedFuncs(t *testing.T) {
	src := "package x\n\n" +
		"import \"errors\"\n\n" +
		"func Untouched() error { return errors.New(\"keep\") }\n\n" +
		"func Changed() int { return 41 }\n"
	// pretend the diff changed only the Changed() func (line 7 of the new file)
	changedLines := map[int]bool{7: true}
	out, neutered, err := neuterFuncsInSource("x.go", []byte(src), changedLines)
	if err != nil {
		t.Fatal(err)
	}
	if len(neutered) != 1 || neutered[0] != "Changed" {
		t.Fatalf("neutered funcs = %v, want [Changed]", neutered)
	}
	s := string(out)
	if !strings.Contains(s, `panic("mutation-gate`) {
		t.Errorf("Changed body should be replaced with a panic; got:\n%s", s)
	}
	if !strings.Contains(s, `errors.New("keep")`) {
		t.Errorf("Untouched func must be preserved; got:\n%s", s)
	}
}

func TestCheckMutationSurvival_FlagsSurvivor(t *testing.T) {
	ws := t.TempDir()
	pkg := filepath.Join(ws, "pkg/x")
	_ = os.MkdirAll(pkg, 0o755)
	_ = os.WriteFile(filepath.Join(pkg, "x.go"),
		[]byte("package x\n\nfunc Add(a, b int) int { return a + b }\n"), 0o644)
	_ = os.WriteFile(filepath.Join(pkg, "x_test.go"),
		[]byte("package x\n\nimport \"testing\"\n\nfunc TestAdd(t *testing.T){ _ = Add }\n"), 0o644)

	runner := func(_ context.Context, _ string, _ []string, name string, args ...string) (string, error) {
		switch {
		case name == "git" && args[0] == "status":
			return " M pkg/x/x.go\x00 M pkg/x/x_test.go\x00", nil
		case name == "git" && args[0] == "diff" && len(args) > 2 && args[1] == "-U0" && args[2] == "HEAD":
			return "@@ -0,0 +3 @@\n+func Add(a, b int) int { return a + b }\n", nil
		case name == "go" && args[0] == "test":
			return "ok", nil // weak test passes even with the body neutered -> SURVIVOR
		}
		return "", nil
	}
	failed, out := checkMutationSurvival(context.Background(), ws, runner)
	if !failed {
		t.Fatal("expected a survivor: weak test passes against neutered Add")
	}
	if !strings.Contains(out, "pkg/x") || !strings.Contains(out, "Add") {
		t.Errorf("feedback must name the package and surviving func; got:\n%s", out)
	}
}

func TestCheckMutationSurvival_PassesWhenTestsBite(t *testing.T) {
	ws := t.TempDir()
	pkg := filepath.Join(ws, "pkg/x")
	_ = os.MkdirAll(pkg, 0o755)
	orig := "package x\n\nfunc Add(a, b int) int { return a + b }\n"
	_ = os.WriteFile(filepath.Join(pkg, "x.go"), []byte(orig), 0o644)
	_ = os.WriteFile(filepath.Join(pkg, "x_test.go"), []byte("package x\n"), 0o644)

	runner := func(_ context.Context, _ string, _ []string, name string, args ...string) (string, error) {
		switch {
		case name == "git" && args[0] == "status":
			return " M pkg/x/x.go\x00 M pkg/x/x_test.go\x00", nil
		case name == "git" && args[0] == "diff" && len(args) > 2 && args[1] == "-U0" && args[2] == "HEAD":
			return "@@ -0,0 +3 @@\n+func Add(a, b int) int { return a + b }\n", nil
		case name == "go" && args[0] == "test":
			return "FAIL", context.DeadlineExceeded // non-nil -> tests failed under neuter -> they bite
		}
		return "", nil
	}
	failed, _ := checkMutationSurvival(context.Background(), ws, runner)
	if failed {
		t.Fatal("must pass: tests fail under neuter (they bite)")
	}
	got, _ := os.ReadFile(filepath.Join(pkg, "x.go"))
	if string(got) != orig {
		t.Fatalf("x.go not restored; got:\n%s", got)
	}
}

// TestNeuterAndTestPackage_RealGoTest exercises the AST rewrite + a real
// `go test`: it copies the weak-test fixture module into a temp dir, neuters
// Add's body, and confirms the weak test still passes (a true survivor),
// proving the neutered source compiles and the survival signal is real.
func TestNeuterAndTestPackage_RealGoTest(t *testing.T) {
	ws := t.TempDir()
	copyTree(t, "testdata/mutation/weak", filepath.Join(ws, "weak"))

	orig, err := os.ReadFile(filepath.Join(ws, "weak/calc.go"))
	if err != nil {
		t.Fatal(err)
	}
	neutered, names, err := neuterFuncsInSource("calc.go", orig, map[int]bool{3: true})
	if err != nil || len(names) != 1 || names[0] != "Add" {
		t.Fatalf("neuter failed: err=%v names=%v", err, names)
	}
	if err := os.WriteFile(filepath.Join(ws, "weak/calc.go"), neutered, 0o644); err != nil {
		t.Fatal(err)
	}
	weakDir := filepath.Join(ws, "weak")
	if _, err := execCommandRunner(context.Background(), weakDir, nil, "go", "test", "./..."); err != nil {
		t.Fatalf("weak test should PASS under neuter (survivor), got err: %v", err)
	}
}

func TestAddedDiffLines_ReturnsAddedContentExcludingHeaders(t *testing.T) {
	diff := "diff --git a/x b/x\n--- a/x\n+++ b/x\n@@ -1,0 +2,2 @@\n" +
		"+  expr: rate(vllm:request_failure_total[5m])\n" +
		"+  labels: {}\n"
	run := func(_ context.Context, _ string, _ []string, name string, args ...string) (string, error) {
		return diff, nil
	}
	got := addedDiffLines(context.Background(), "/ws", "main", run)
	want := []string{"  expr: rate(vllm:request_failure_total[5m])", "  labels: {}"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("addedDiffLines = %#v, want %#v", got, want)
	}
}

func TestAddedDiffLines_NilOnGitError(t *testing.T) {
	run := func(_ context.Context, _ string, _ []string, name string, args ...string) (string, error) {
		return "", errors.New("boom")
	}
	if got := addedDiffLines(context.Background(), "/ws", "main", run); got != nil {
		t.Fatalf("want nil on git error, got %#v", got)
	}
}

// TestAddedDiffLines_CommittedVsUncommitted is the regression test for the
// coder grounding rail's placement bug: addedDiffLines reads the committed
// diff (base...HEAD), so a NEW file the coder wrote is invisible until it is
// committed. The rail therefore MUST run after repo.Commit in runLLMPath, not
// before it (where the earlier no-op-forever bug lived). This exercises real
// git rather than a stubbed runner, since the stub is what let the bug hide.
func TestAddedDiffLines_CommittedVsUncommitted(t *testing.T) {
	ws := t.TempDir()
	git := func(args ...string) string {
		t.Helper()
		out, err := execCommandRunner(context.Background(), ws, nil, "git", args...)
		if err != nil {
			t.Fatalf("git %s: %v: %s", strings.Join(args, " "), err, out)
		}
		return out
	}
	git("init", "-q")
	git("config", "user.email", "t@t.io")
	git("config", "user.name", "t")
	if err := os.WriteFile(filepath.Join(ws, "base.txt"), []byte("base\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	git("add", "-A")
	git("commit", "-q", "-m", "base")
	git("branch", "-M", "main")
	git("checkout", "-q", "-b", "feature")

	// The coder writes a NEW file containing a hallucinated metric identifier.
	metricLine := "  expr: rate(vllm:request_failure_total[5m])"
	if err := os.WriteFile(filepath.Join(ws, "alerts.yaml"), []byte(metricLine+"\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	// Uncommitted: base...HEAD sees nothing (this is the bug the fix avoids).
	if got := addedDiffLines(context.Background(), ws, "main", execCommandRunner); len(got) != 0 {
		t.Fatalf("pre-commit addedDiffLines should be empty (new file untracked), got %#v", got)
	}

	// After commit: the new file's added line is visible to base...HEAD.
	git("add", "-A")
	git("commit", "-q", "-m", "add alerts")
	got := addedDiffLines(context.Background(), ws, "main", execCommandRunner)
	found := false
	for _, l := range got {
		if strings.Contains(l, "vllm:request_failure_total") {
			found = true
		}
	}
	if !found {
		t.Fatalf("post-commit addedDiffLines should include the new file's metric line, got %#v", got)
	}
}

// copyTree copies a flat directory of files (test helper).
func copyTree(t *testing.T, src, dst string) {
	t.Helper()
	entries, err := os.ReadDir(src)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(dst, 0o755); err != nil {
		t.Fatal(err)
	}
	for _, e := range entries {
		data, err := os.ReadFile(filepath.Join(src, e.Name()))
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(dst, e.Name()), data, 0o644); err != nil {
			t.Fatal(err)
		}
	}
}

// TestCheckPerHunkCoverage_ReportsUncoveredWiringLine is the regression test
// for #1694: a diff with two added hunks in an envtest package, where the
// first hunk is covered (reverting it fails a test) and the second is a one
// line wiring addition that no test exercises (reverting it passes). The
// per-hunk pass must report exactly the second hunk, named by file and line
// range, and nothing else.
func TestCheckPerHunkCoverage_ReportsUncoveredWiringLine(t *testing.T) {
	ws := t.TempDir()
	_ = os.MkdirAll(filepath.Join(ws, "internal/controller"), 0o755)
	// The changed production file (HEAD content). The two hunks are the covered
	// logic line and the uncovered wiring line appended to rollup.
	_ = os.WriteFile(
		filepath.Join(ws, "internal/controller/rollup.go"),
		[]byte("package controller\n\nfunc rollup() {\n\t_ = compute()\n\temitContradiction()\n}\n"),
		0o644)

	// The diff against the base (merge-base) has two added hunks: the covered
	// line at 3-4 and the uncovered wiring line at 5.
	diffOut := "diff --git a/internal/controller/rollup.go b/internal/controller/rollup.go\n" +
		"@@ -0,0 +1,4 @@\n+package controller\n+\n+func rollup() {\n+\t_ = compute()\n" +
		"@@ -0,0 +5 @@\n+\temitContradiction()\n"
	// testCalls counts go test invocations so the runner can fail the first
	// revert (covered hunk) and pass the second (uncovered wiring line).
	testCalls := 0
	runner := func(_ context.Context, _ string, _ []string, name string, args ...string) (string, error) {
		switch {
		case name == "git" && len(args) > 1 && args[0] == "diff" && containsStr(args, "--name-only"):
			// changedFilesFromDiff reads the name-only view.
			return "internal/controller/rollup.go\n", nil
		case name == "git" && len(args) > 1 && args[0] == "diff" && containsStr(args, "-U0"):
			// splitProductionHunks reads the -U0 diff with line ranges.
			return diffOut, nil
		case name == "go" && len(args) > 0 && args[0] == "test":
			testCalls++
			if testCalls == 1 {
				// First revert (covered hunk 1-4): a test fails -> covered.
				return "FAIL", errors.New("boom")
			}
			// Second revert (uncovered wiring line 5): tests pass -> uncovered.
			return "", nil
		}
		return "", nil
	}

	findings := CheckPerHunkCoverage(context.Background(), ws, "main", runner)
	if len(findings) != 1 {
		t.Fatalf("want exactly one uncovered hunk, got %d: %#v", len(findings), findings)
	}
	if findings[0].Dir != "internal/controller" || findings[0].File != "internal/controller/rollup.go" {
		t.Errorf("unexpected finding: %#v", findings[0])
	}
	if findings[0].LineRange != "5-5" {
		t.Errorf("LineRange = %q, want 5-5 (the uncovered wiring line)", findings[0].LineRange)
	}
}

// TestCheckPerHunkCoverage_AllCoveredReportsClean is the companion fixture:
// a diff whose every added hunk is covered (each revert fails a test). The
// per-hunk pass must report nothing.
func TestCheckPerHunkCoverage_AllCoveredReportsClean(t *testing.T) {
	ws := t.TempDir()
	_ = os.MkdirAll(filepath.Join(ws, "internal/controller"), 0o755)
	_ = os.WriteFile(
		filepath.Join(ws, "internal/controller/rollup.go"),
		[]byte("package controller\n\nfunc rollup() {\n\t_ = compute()\n\temitContradiction()\n}\n"),
		0o644)
	diffOut := "diff --git a/internal/controller/rollup.go b/internal/controller/rollup.go\n" +
		"@@ -0,0 +1,4 @@\n+package controller\n+\n+func rollup() {\n+\t_ = compute()\n" +
		"@@ -0,0 +5 @@\n+\temitContradiction()\n"
	runner := func(_ context.Context, _ string, _ []string, name string, args ...string) (string, error) {
		switch {
		case name == "git" && len(args) > 1 && args[0] == "diff" && containsStr(args, "--name-only"):
			return "internal/controller/rollup.go\n", nil
		case name == "git" && len(args) > 1 && args[0] == "diff" && containsStr(args, "-U0"):
			return diffOut, nil
		case name == "go" && len(args) > 0 && args[0] == "test":
			// Every reverted hunk fails a test -> every hunk is covered.
			return "FAIL", errors.New("boom")
		}
		return "", nil
	}

	findings := CheckPerHunkCoverage(context.Background(), ws, "main", runner)
	if len(findings) != 0 {
		t.Fatalf("want no uncovered hunks, got %d: %#v", len(findings), findings)
	}
}

// TestCheckPerHunkCoverage_CompileFailureCountsAsCovered verifies that a
// compile failure on a reverted hunk counts as covered (not uncovered): the
// hunk is load-bearing for code that is exercised. Only a clean green run
// means uncovered.
func TestCheckPerHunkCoverage_CompileFailureCountsAsCovered(t *testing.T) {
	ws := t.TempDir()
	_ = os.MkdirAll(filepath.Join(ws, "internal/controller"), 0o755)
	_ = os.WriteFile(
		filepath.Join(ws, "internal/controller/rollup.go"),
		[]byte("package controller\n\nfunc rollup() {\n\temitContradiction()\n}\n"),
		0o644)
	diffOut := "diff --git a/internal/controller/rollup.go b/internal/controller/rollup.go\n" +
		"@@ -0,0 +1,3 @@\n+package controller\n+\n+func rollup() {\n+\temitContradiction()\n}\n"
	runner := func(_ context.Context, _ string, _ []string, name string, args ...string) (string, error) {
		switch {
		case name == "git" && len(args) > 1 && args[0] == "diff":
			return diffOut, nil
		case name == "go" && len(args) > 0 && args[0] == "test":
			// A non-nil error (compile break) means the hunk is covered.
			return "FAIL", errors.New("build failed")
		}
		return "", nil
	}

	findings := CheckPerHunkCoverage(context.Background(), ws, "main", runner)
	if len(findings) != 0 {
		t.Fatalf("compile failure must count as covered, got %d findings: %#v", len(findings), findings)
	}
}

// containsStr reports whether args contains target.
func containsStr(args []string, target string) bool {
	for _, a := range args {
		if a == target {
			return true
		}
	}
	return false
}

// TestCheckPerHunkCoverage_BoundedAndReportsTruncation verifies the pass is
// bounded and says so. Every hunk costs a full `go test`, so an unbounded loop
// lets a sprawling envtest diff overrun the gate deadline -- and a gate that
// overruns reads as broken, not slow. Layer 2 bounds itself the same way.
//
// The truncation notice is the load-bearing half: a bounded pass that reported
// nothing would be indistinguishable from a clean one, so "no findings" would
// read as "fully covered" when most packages were never checked.
func TestCheckPerHunkCoverage_BoundedAndReportsTruncation(t *testing.T) {
	ws := t.TempDir()
	// More envtest packages than the bound allows.
	nPkgs := maxPerHunkPackages + 3
	var names []string
	for i := 0; i < nPkgs; i++ {
		dir := filepath.Join("internal", "controller", "sub"+strconv.Itoa(i))
		_ = os.MkdirAll(filepath.Join(ws, dir), 0o755)
		_ = os.WriteFile(filepath.Join(ws, dir, "x.go"),
			[]byte("package controller\n\nfunc f() {\n\tg()\n}\n"), 0o644)
		names = append(names, filepath.Join(dir, "x.go"))
	}
	diffOut := "diff --git a/x b/x\n@@ -0,0 +4 @@\n+\tg()\n"

	runner := func(_ context.Context, _ string, _ []string, name string, args ...string) (string, error) {
		switch {
		case name == "git" && len(args) > 1 && args[0] == "diff" && containsStr(args, "--name-only"):
			return strings.Join(names, "\n") + "\n", nil
		case name == "git" && len(args) > 1 && args[0] == "diff" && containsStr(args, "-U0"):
			return diffOut, nil
		case name == "go" && len(args) > 0 && args[0] == "test":
			// Green: every hunk would be reported uncovered, so any package the
			// bound skipped is visible as a missing finding.
			return "ok", nil
		}
		return "", nil
	}

	findings := CheckPerHunkCoverage(context.Background(), ws, "main", runner)

	var truncation string
	pkgFindings := 0
	for _, f := range findings {
		if f.Dir == "" && f.LineRange == "" {
			truncation = f.File
			continue
		}
		pkgFindings++
	}
	if truncation == "" {
		t.Fatalf("bounded run reported no truncation notice; %d findings would read as a complete pass", len(findings))
	}
	if pkgFindings > maxPerHunkPackages {
		t.Fatalf("checked %d packages, bound is %d", pkgFindings, maxPerHunkPackages)
	}
}

// TestSplitProductionHunks_DropsCommentOnlyHunk is the regression test for
// #1735: an added block that contains only "//" comment lines carries no Go
// statement, so reverting it can never turn a test red and the per-hunk pass
// would report it uncovered forever. splitProductionHunks must not emit it as
// a candidate at all.
func TestSplitProductionHunks_DropsCommentOnlyHunk(t *testing.T) {
	diff := "diff --git a/x/x.go b/x/x.go\n" +
		"@@ -0,0 +3,2 @@\n+// first comment\n+// second comment\n"
	run := func(_ context.Context, _ string, _ []string, _ string, _ ...string) (string, error) {
		return diff, nil
	}
	got := splitProductionHunks(context.Background(), "/ws", "main", "x/x.go", run)
	if len(got) != 0 {
		t.Fatalf("comment-only hunk must be dropped, got %d hunks: %#v", len(got), got)
	}
}

// TestSplitProductionHunks_KeepsMixedHunk is the boundary test: a hunk that
// mixes a comment line and a real statement still contains a plausible Go
// statement, so it MUST be kept. Dropping it would silently stop checking real
// code that happens to sit next to a comment.
func TestSplitProductionHunks_KeepsMixedHunk(t *testing.T) {
	diff := "diff --git a/x/x.go b/x/x.go\n" +
		"@@ -0,0 +3,2 @@\n+// comment above the statement\n+\t_ = compute()\n"
	run := func(_ context.Context, _ string, _ []string, _ string, _ ...string) (string, error) {
		return diff, nil
	}
	got := splitProductionHunks(context.Background(), "/ws", "main", "x/x.go", run)
	if len(got) != 1 {
		t.Fatalf("mixed hunk must be kept, got %d hunks: %#v", len(got), got)
	}
	if got[0].LineRange != "3-4" {
		t.Errorf("LineRange = %q, want 3-4", got[0].LineRange)
	}
}

// TestSplitProductionHunks_DropsBlankOnlyHunk verifies a hunk of only blank
// lines is also not a candidate: it carries no statement either, so it would
// hit the same false positive.
func TestSplitProductionHunks_DropsBlankOnlyHunk(t *testing.T) {
	diff := "diff --git a/x/x.go b/x/x.go\n" +
		"@@ -0,0 +3,2 @@\n+\n+\n"
	run := func(_ context.Context, _ string, _ []string, _ string, _ ...string) (string, error) {
		return diff, nil
	}
	got := splitProductionHunks(context.Background(), "/ws", "main", "x/x.go", run)
	if len(got) != 0 {
		t.Fatalf("blank-only hunk must be dropped, got %d hunks: %#v", len(got), got)
	}
}
