apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "rocm-smi-exporter.fullname" . }}
  namespace: {{ include "rocm-smi-exporter.namespace" . }}
  labels:
    {{- include "rocm-smi-exporter.labels" . | nindent 4 }}
spec:
  updateStrategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "rocm-smi-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: rocm-smi-exporter
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "rocm-smi-exporter.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rocm-smi-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- with .Values.extraInitContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
      - name: rocm-smi-exporter
        image: {{ include "rocm-smi-exporter.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - --rocm-smi.interval=10s
        - --collector.gpu.temp
        - --collector.gpu.power
        - --collector.gpu.utilization
        ports:
        - name: metrics
          containerPort: 9515
          protocol: TCP
        {{- with .Values.env }}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: sys-class-drm
          mountPath: /sys/class/drm
          readOnly: true
        - name: var-lib-rocm
          mountPath: /var/lib/rocm
          readOnly: true
        {{- with .Values.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.extraContainers }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
      volumes:
      - name: sys-class-drm
        hostPath:
          path: /sys/class/drm
          type: Directory
      - name: var-lib-rocm
        hostPath:
          path: /var/lib/rocm
          type: Directory
      {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
      terminationGracePeriodSeconds: 30
