apiVersion: v1
kind: Service
metadata:
  name: {{ include "rocm-smi-exporter.fullname" . }}
  labels:
    {{- include "rocm-smi-exporter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.scrape.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "rocm-smi-exporter.selectorLabels" . | nindent 4 }}
